### ISSUE TITLE
No SQL Tables

### ISSUE THREAD

**Issue by bishopgodsey** [diokey/cathedral#3]
There is no SQL tables for importing or code to install some. Cannot test it without them.

**Comment by diokey** [comment]
I will update include the database as soon as possible.

Just FYI, I didn't get a chance to finish this project. You are welcome to continue

**Comment by diokey** [comment]
Added the database. You will also need to have Mod_Rewrite enable in your apache.
For reference https://www.digitalocean.com/community/tutorials/how-to-set-up-mod_rewrite
